spring.datasource.url=jdbc:postgresql://postgres:5432/hobbyrent_db
spring.datasource.username=postgres
spring.datasource.password=novyi_parol_123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true